# Generated by Django 5.2.7 on 2026-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_city', models.CharField(max_length=50)),
                ('price_ticket', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
